version: "3.8"

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./files:/app/files
    restart: unless-stopped

  metabase:
    image: metabase/metabase
    depends_on:
      - postgres
    ports:
      - "3000:3000"     # доступ к Metabase через VPN: http://company-server:3000
    volumes:
      - metabase-data:/metabase-data
    restart: unless-stopped
    environment:
    # при желании можно задать переменные окружения для Metabase (но не обязательно)
    # MB_JETTY_HOST: "0.0.0.0"
    # MB_DB_FILE: /metabase-data/metabase.db
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:3000/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  pgdata: